import Foundation

// Generated from kmp/.../Strings.kt by hand-port; same keys, same six languages.
enum L {
    static let en: [String: String] = [
        "clear": "Clear",
        "parabola": "Parabola",
        "exponential": "Exponential",
        "sine": "Sine",
        "hyperbola": "Hyperbola",
        "circle": "Circle",
        "arc": "Arc",
        "measured": "MEASURED FROM THE DRAWING",
        "hint": "Draw a curve, or pick an example.",
        "samples": "Samples",
        "xrange": "x range",
        "yrange": "y range",
        "roots": "Crosses y=0 at",
        "branch": "Branch",
        "family": "Family",
        "circlefit": "Circle fit",
        "never": "never",
        "horizontal": "horizontal",
        "vertical": "vertical",
        "curved": "slanted / curved",
        "none": "none of the three",
        "notcircle": "not a circle",
        "centre": "centre",
        "linear": "linear",
        "quadratic": "quadratic",
        "exponentialf": "exponential",
    ]
    static let es: [String: String] = [
        "clear": "Borrar",
        "parabola": "Parábola",
        "exponential": "Exponencial",
        "sine": "Seno",
        "hyperbola": "Hipérbola",
        "circle": "Círculo",
        "arc": "Arco",
        "measured": "MEDIDO DEL DIBUJO",
        "hint": "Dibuja una curva o elige un ejemplo.",
        "samples": "Muestras",
        "xrange": "rango x",
        "yrange": "rango y",
        "roots": "Cruza y=0 en",
        "branch": "Rama",
        "family": "Familia",
        "circlefit": "Ajuste circular",
        "never": "nunca",
        "horizontal": "horizontal",
        "vertical": "vertical",
        "curved": "inclinada / curva",
        "none": "ninguna de las tres",
        "notcircle": "no es un círculo",
        "centre": "centro",
        "linear": "lineal",
        "quadratic": "cuadrática",
        "exponentialf": "exponencial",
    ]
    static let fr: [String: String] = [
        "clear": "Effacer",
        "parabola": "Parabole",
        "exponential": "Exponentielle",
        "sine": "Sinus",
        "hyperbola": "Hyperbole",
        "circle": "Cercle",
        "arc": "Arc",
        "measured": "MESURÉ SUR LE DESSIN",
        "hint": "Dessinez une courbe ou choisissez un exemple.",
        "samples": "Échantillons",
        "xrange": "plage x",
        "yrange": "plage y",
        "roots": "Coupe y=0 en",
        "branch": "Branche",
        "family": "Famille",
        "circlefit": "Cercle ajusté",
        "never": "jamais",
        "horizontal": "horizontale",
        "vertical": "verticale",
        "curved": "inclinée / courbe",
        "none": "aucune des trois",
        "notcircle": "pas un cercle",
        "centre": "centre",
        "linear": "linéaire",
        "quadratic": "quadratique",
        "exponentialf": "exponentielle",
    ]
    static let de: [String: String] = [
        "clear": "Löschen",
        "parabola": "Parabel",
        "exponential": "Exponential",
        "sine": "Sinus",
        "hyperbola": "Hyperbel",
        "circle": "Kreis",
        "arc": "Bogen",
        "measured": "AUS DER ZEICHNUNG GEMESSEN",
        "hint": "Zeichne eine Kurve oder wähle ein Beispiel.",
        "samples": "Proben",
        "xrange": "x-Bereich",
        "yrange": "y-Bereich",
        "roots": "Schneidet y=0 bei",
        "branch": "Ast",
        "family": "Familie",
        "circlefit": "Kreisanpassung",
        "never": "nie",
        "horizontal": "waagrecht",
        "vertical": "senkrecht",
        "curved": "schräg / gekrümmt",
        "none": "keine der drei",
        "notcircle": "kein Kreis",
        "centre": "Mitte",
        "linear": "linear",
        "quadratic": "quadratisch",
        "exponentialf": "exponentiell",
    ]
    static let ja: [String: String] = [
        "clear": "消去",
        "parabola": "放物線",
        "exponential": "指数関数",
        "sine": "正弦",
        "hyperbola": "双曲線",
        "circle": "円",
        "arc": "弧",
        "measured": "描画から計測",
        "hint": "曲線を描くか、例を選んでください。",
        "samples": "サンプル数",
        "xrange": "x範囲",
        "yrange": "y範囲",
        "roots": "y=0との交点",
        "branch": "枝",
        "family": "種類",
        "circlefit": "円の当てはめ",
        "never": "なし",
        "horizontal": "水平",
        "vertical": "垂直",
        "curved": "斜め / 曲線",
        "none": "三種のいずれでもない",
        "notcircle": "円ではない",
        "centre": "中心",
        "linear": "一次",
        "quadratic": "二次",
        "exponentialf": "指数",
    ]
    static let zh: [String: String] = [
        "clear": "清除",
        "parabola": "抛物线",
        "exponential": "指数",
        "sine": "正弦",
        "hyperbola": "双曲线",
        "circle": "圆",
        "arc": "弧",
        "measured": "从图形中测得",
        "hint": "画一条曲线，或选择一个示例。",
        "samples": "采样数",
        "xrange": "x 范围",
        "yrange": "y 范围",
        "roots": "与 y=0 交于",
        "branch": "分支",
        "family": "类型",
        "circlefit": "圆拟合",
        "never": "无",
        "horizontal": "水平",
        "vertical": "垂直",
        "curved": "倾斜 / 弯曲",
        "none": "三者皆非",
        "notcircle": "不是圆",
        "centre": "圆心",
        "linear": "线性",
        "quadratic": "二次",
        "exponentialf": "指数",
    ]
    static let all = ["en": en, "es": es, "fr": fr, "de": de, "ja": ja, "zh": zh]
    static var language = Locale.current.language.languageCode?.identifier ?? "en"
    static subscript(_ key: String) -> String { (all[language] ?? en)[key] ?? en[key] ?? key }
}
